### ISSUE TITLE
Upgrade to SIDH v1.1?

### ISSUE THREAD

**Issue by tristanhoy** [cyph/sidh.js#1]
According to the Microsoft page, the latest 1.1 version includes compressed 564 byte public keys - however the public keys generated by this library are 1536 bytes, so I'm assuming you're using the old 1.0 version.

Looking at the [mirror Github repository](https://github.com/dconnolly/msr-sidh), it seems like this was released recently (it was applied to the mirror a mere 4 days after your last commit to this repo).

The 1.1 release also includes several performance improvements - "optimized public key validation, and further optimizations to isogeny, curve, and field arithmetic". Anything that could speed this algorithm up would be most welcome!

**Comment by buu700** [comment]
Awesome, thanks for letting me know; we actually aren't currently using this for anything because of the poor performance, so hopefully 1.1 makes a difference. (It looks like 1.1 was actually released back in December and I just wasn't aware at the time.)

I'll play around with the update and publish a new version of this right away if it has no breaking changes.

**Comment by buu700** [comment]
Okay, just published the 1.1 update. It's a bit faster, but nothing really game-changing; the example lines from the readme take 3.5 - 4 seconds for me vs 5.5 - 6 seconds with the previous version.

As far as the public key size, it's gone down from 1536 bytes to 1152. The reasons that it isn't 564 bytes are:

1. SIDH has two separate concepts of "Alice key pairs" and "Bob key pairs". In order to provide a more traditional public key crypto API, sidh.js's `keyPair` function is actually generating and combining two key pairs (one "Alice key pair" and one "Bob key pair"), doubling the effective public key and private key sizes.

2. Not sure if I ever looked into why this was the case, but SIDH throws an error if the number of bytes I allocate for the public key isn't a multiple of 32, so I had to make the base public key size 576 instead of 564 — which x2 is 1152.

If you're interested in getting around this limitation, there's a lower-level API at `sidh.base` that makes you specify `isAlice` when generating a key pair and gives you the option to disable the public key validation step of generating the secret. It isn't documented in the type definition or the readme, but you can see what the `sidh.base` interface looks like [here](https://github.com/cyph/sidh.js/blob/3854f79/post.js#L87).

**Comment by tristanhoy** [comment]
Thanks for the notes on public key size, and for providing a simplified API.

With regards to performance, the shared secret generation is now more than 2x faster (1800ms to 800ms on my machine). This is massive!

This makes the use of SIDH slightly more feasible for non-interactive authenticated exchange of long-term shared secrets where perfect forward secrecy is not a requirement.

For everything else, there's RWLE :) And thanks for bringing so many post-quantum crypto transpiles to Node! It's great to actually play with these algorithms on my platform of choice.

**Comment by buu700** [comment]
Awesome, glad it helped! Not a problem at all; it's fun to keep up with post-quantum crypto developments for @cyph, and these modules mostly share the same boilerplate code so it hasn't been too much work after the first one (ntru.js).
